apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-storage
  namespace: nexus
  labels: 
    app: nexus-storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nexus-storage-data
  resources:
    requests:
      storage: 2Gi
