---
- hosts: sonar_host
  user: root 
  become_method: sudo
  gather_facts: True
  connection: local
  tasks:
    - include_vars: vars/input.json
    - include_vars: SonarParams.yml
    #- name: accept new ssh fingerprints
     # shell: ssh-keyscan -H {{ host_ip }} >> ~/.ssh/known_hosts
      #- name: Add IP to ec2_hosts group
      #  local_action: add_host hostname={{ host_ip }} groupname=launched
      #when: AWS is ENV
      #- name: Add IP to VM_hosts group
      #      local_action: add_host hostname={{ host_ip }} ansible_sudo_pass={{ password }} ansible_ssh_pass={{ password }} groupname=launched
      #      when: VM is ENV


- include:  AWS.yml
  
- include: SonarOutput.yml 
