#Storage class for Nexus
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-storage-data
  labels:
    app: jenkins
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-2a
allowVolumeExpansion: true
