apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  labels:
    app: jenkins
spec:
  storageClassName: jenkins-storage-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: default
#   volumeName: jenkins
