---
#Deployment for Postgres
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata: 
      name: postgresql
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgreqsl
          image: postgres:9.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgresql-port
          env:
            - name: POSTGRES_USER
              value: sonar
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
#service for POSTGRES
kind: Service
apiVersion: v1
metadata:
  name: postgresql-db
  labels:
    name: postgresql-db
spec:
        #  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql-db-port
  selector:
    app: postgresql

---
#PV for sonar
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres-pvc
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels: 
    app: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 4Gi

---
#Storage class for Postgres
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage
  labels: 
    app: postgres-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-2a
allowVolumeExpansion: true
