apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: hcl-app
type: Opaque
data:
        #  ROOT_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3JkCg==
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: dGVzdDEyMw== #test123
